### ISSUE TITLE
bug update homebrew

### ISSUE THREAD

**Issue by THZoria** [PoloNX/AtmoPackUpdater#13]
Bug on the homebrew download system, the update is done correctly but the old version of the homebrew is not deleted which makes a duplicate version in the switch folder

**Comment by PoloNX** [comment]
Normally it was fixed in the last version. Try to delete all your older version and keep the earlier

**Comment by THZoria** [comment]
The incident still occurs in version 1.8.2, we noticed it on the discord in the morning

**Comment by PoloNX** [comment]
I’ll try to investigate soon

**Comment by PoloNX** [comment]
Fixed in the last commit
