### ISSUE TITLE
App crashes while trying to update Sigpatches

### ISSUE THREAD

**Issue by flo0306** [PoloNX/AtmoPackUpdater#15]
I tried twice to update Sigpatches but when the console asks for a reboot after downloading the files, the screen froze. I'm using a Mariko Switch. I suspect the rebooting sequence is may be not appropriate to Mariko. Files were not installed after a clean reboot.

**Comment by PoloNX** [comment]
Hi, I never have the ability to test the super over mariko. I’ll try to add this functionality with others bug fix on the future update. Thanks for the report

**Comment by flo0306** [comment]
No problem, thank you for the feedback and for your tool ;)

**Comment by PoloNX** [comment]
Normally I fixed the issue in the last commit. Try the 1.9.0 when you want !

**Comment by flo0306** [comment]
I tried with the last release 1.9.0 and the app still freeze as before :(

**Comment by PoloNX** [comment]
Sigpatches are extracted ?

**Comment by flo0306** [comment]
Yes there are ! Only the ones in "atmosphere" folder but not the patches.ini on "bootloader" folder.

**Comment by PoloNX** [comment]
It's hard for me to test this. Every other updates works on one mariko unit ?

**Comment by PoloNX** [comment]
I pinned the issue. If someone have one idea for one solution put it here

**Comment by flo0306** [comment]
I’ve been able to update the app itself and some homebrews without any issues. On Mariko it is not possible to reboot directly to any payload. I don’t know how you manage the reboot sequence. Do you call any specific file on SD card ? just some ideas

**Comment by PoloNX** [comment]
For example for the cfw I just rename the payload you're using "payload.bin.temp" and put one payload names "payload.bin" at the root of the sd card. After this when you will boot on the payload.bin it will apply the update of the firmware and the payload "payload.bin.temp" will be renamed "payload.bin" and you have to reboot a new time the switch. I do the same thing for sigpatches.

The update of the pack is working ?

**Comment by flo0306** [comment]
I didn’t update the full pack because I do not use all the homebrew you proposed. Otherwise, I have also used AIO updater to update Atmosphere and Hekate and it worked.

**Comment by PoloNX** [comment]
I see. I don’t know what to do to debug this issue
